name: FusionFX-Autopilot
description: >
  Fully autonomous AI trading bot that evolves strategies using RL and executes Forex trades via OANDA.
  Built to compound $300 to $1.5M+ in 60 days, then sustain autonomous profit delivery over 50+ years.

language: python
features:
  - multi-agent coordination
  - reinforcement learning
  - docker orchestration
  - crypto withdrawal logic
  - quantum-safe key rotation
  - DAO governance
  - compliance monitoring
  - telegram & SMS alerts

tasks:
  - Build missing agent scaffolds
  - Review and validate deployment logic
  - Add tests for risk_kernel and strategist_agent
  - Optimize docker-compose startup
  - Document AI architecture

monorepo: true
