version: '3.9'

services:
  strategist:
    build: ..
    container_name: strategist
    command: python core/strategist_agent.py
    restart: unless-stopped

  meta_controller:
    build: ..
    container_name: meta_controller
    command: python core/meta_controller.py
    restart: unless-stopped

  profit_manager:
    build: ..
    container_name: profit_manager
    command: python core/profit_manager.py
    restart: unless-stopped

  dao_governor:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ../:/usr/src/app
    command: node agents/dao_governor.mjs
    container_name: dao_governor
    restart: unless-stopped

  cloud_nomad:
    build: ..
    container_name: cloud_nomad
    command: python agents/cloud_nomad.py
    restart: unless-stopped

  depin_manager:
    build: ..
    container_name: depin_manager
    command: python agents/depin_manager.py
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: grafana-dashboard
    restart: unless-stopped

networks:
  default:
    driver: bridge